# Development 환경용 override 설정
# docker-compose up 시 자동으로 적용됩니다.

version: '3.8'

services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./infrastructure/init-data.sql:/docker-entrypoint-initdb.d/init-data.sql

  kafka:
    environment:
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"

  member-service:
    build:
      context: ./member-service
      dockerfile: Dockerfile
    volumes:
      - ./member-service:/app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    depends_on:
      - mysql
      - kafka

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    volumes:
      - ./product-service:/app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    depends_on:
      - mysql
      - kafka

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    volumes:
      - ./order-service:/app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    depends_on:
      - mysql
      - kafka
      - member-service
      - product-service
      - payment-service

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    volumes:
      - ./payment-service:/app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    depends_on:
      - mysql
      - kafka
      - member-service

volumes:
  mysql_dev_data:
